package com.novel.auth.application.service;

import com.novel.auth.common.exception.BusinessException;
import com.novel.auth.domain.model.AccountStatus;
import com.novel.auth.domain.model.User;
import com.novel.auth.domain.model.UserId;
import com.novel.auth.domain.repository.UserRepository;
import com.novel.auth.domain.service.PasswordDomainService;
import com.novel.auth.interfaces.rest.dto.LoginRequest;
import com.novel.auth.interfaces.rest.dto.LoginResponse;
import com.novel.auth.interfaces.rest.dto.RegisterRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;

import cn.dev33.satoken.stp.StpUtil;

/**
 * Authentication application service — orchestrates login / register / logout use cases.
 */
@Service
public class AuthAppService {

    private static final Logger log = LoggerFactory.getLogger(AuthAppService.class);

    private final UserRepository userRepository;
    private final PasswordDomainService passwordDomainService;

    public AuthAppService(UserRepository userRepository, PasswordDomainService passwordDomainService) {
        this.userRepository = userRepository;
        this.passwordDomainService = passwordDomainService;
    }

    /**
     * Register a new user account.
     *
     * @param request registration form (username, email, password)
     * @throws BusinessException if username or email already exists
     */
    @Transactional
    public void register(RegisterRequest request) {
        // Check uniqueness
        if (userRepository.existsByUsername(request.getUsername())) {
            throw new BusinessException("用户名已存在");
        }
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new BusinessException("邮箱已被注册");
        }

        // Hash password
        String passwordHash = passwordDomainService.hash(request.getPassword());

        // Create domain entity
        User user = new User(
                new UserId(null),  // ID will be generated by DB
                request.getUsername(),
                request.getEmail(),
                passwordHash,
                AccountStatus.ACTIVE,
                LocalDateTime.now()
        );

        // Persist
        userRepository.save(user);
        log.info("User registered: username={}", request.getUsername());
    }

    /**
     * Authenticate a user and return a session token.
     *
     * @param request login form (username, password)
     * @return login response with token and user info
     * @throws BusinessException if credentials are invalid
     */
    public LoginResponse login(LoginRequest request) {
        // Find user by username
        User user = userRepository.findByUsername(request.getUsername())
                .orElseThrow(() -> new BusinessException("用户名或密码错误"));

        // Verify password
        if (!passwordDomainService.verify(request.getPassword(), user.getPasswordHash())) {
            throw new BusinessException("用户名或密码错误");
        }

        // Check account status
        if (user.getStatus() != AccountStatus.ACTIVE) {
            throw new BusinessException("账户已被禁用");
        }

        // Create Sa-Token session
        StpUtil.login(user.getId().value());
        String token = StpUtil.getTokenValue();

        // Build response
        LoginResponse response = new LoginResponse();
        response.setToken(token);

        LoginResponse.UserInfo userInfo = new LoginResponse.UserInfo();
        userInfo.setUserId(user.getId().value());
        userInfo.setUsername(user.getUsername());
        userInfo.setEmail(user.getEmail());
        userInfo.setPlan(0);  // default free plan
        response.setUserInfo(userInfo);

        log.info("User logged in: username={}", request.getUsername());
        return response;
    }

    /**
     * Logout the current user (invalidate session).
     */
    public void logout() {
        StpUtil.logout();
        log.info("User logged out");
    }
}
