# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_client import auth_service_pb2 as auth__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyToken = channel.unary_unary(
                '/novel.auth.AuthService/VerifyToken',
                request_serializer=auth__service__pb2.VerifyTokenRequest.SerializeToString,
                response_deserializer=auth__service__pb2.VerifyTokenResponse.FromString,
                _registered_method=True)
        self.CheckQuota = channel.unary_unary(
                '/novel.auth.AuthService/CheckQuota',
                request_serializer=auth__service__pb2.CheckQuotaRequest.SerializeToString,
                response_deserializer=auth__service__pb2.CheckQuotaResponse.FromString,
                _registered_method=True)
        self.RecordUsage = channel.unary_unary(
                '/novel.auth.AuthService/RecordUsage',
                request_serializer=auth__service__pb2.RecordUsageRequest.SerializeToString,
                response_deserializer=auth__service__pb2.RecordUsageResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerifyToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyToken,
                    request_deserializer=auth__service__pb2.VerifyTokenRequest.FromString,
                    response_serializer=auth__service__pb2.VerifyTokenResponse.SerializeToString,
            ),
            'CheckQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckQuota,
                    request_deserializer=auth__service__pb2.CheckQuotaRequest.FromString,
                    response_serializer=auth__service__pb2.CheckQuotaResponse.SerializeToString,
            ),
            'RecordUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordUsage,
                    request_deserializer=auth__service__pb2.RecordUsageRequest.FromString,
                    response_serializer=auth__service__pb2.RecordUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'novel.auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('novel.auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerifyToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/novel.auth.AuthService/VerifyToken',
            auth__service__pb2.VerifyTokenRequest.SerializeToString,
            auth__service__pb2.VerifyTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/novel.auth.AuthService/CheckQuota',
            auth__service__pb2.CheckQuotaRequest.SerializeToString,
            auth__service__pb2.CheckQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/novel.auth.AuthService/RecordUsage',
            auth__service__pb2.RecordUsageRequest.SerializeToString,
            auth__service__pb2.RecordUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
