# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_service.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\x12\nnovel.auth\"#\n\x12VerifyTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"U\n\x13VerifyTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0c\n\x04plan\x18\x04 \x01(\x05\"4\n\x11\x43heckQuotaRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"J\n\x12\x43heckQuotaResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x11\n\tremaining\x18\x02 \x01(\x05\x12\x10\n\x08reset_at\x18\x03 \x01(\t\"f\n\x12RecordUsageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x1a\n\x12\x63hapters_processed\x18\x03 \x01(\x05\x12\x13\n\x0btokens_used\x18\x04 \x01(\x03\"&\n\x13RecordUsageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xfa\x01\n\x0b\x41uthService\x12N\n\x0bVerifyToken\x12\x1e.novel.auth.VerifyTokenRequest\x1a\x1f.novel.auth.VerifyTokenResponse\x12K\n\nCheckQuota\x12\x1d.novel.auth.CheckQuotaRequest\x1a\x1e.novel.auth.CheckQuotaResponse\x12N\n\x0bRecordUsage\x12\x1e.novel.auth.RecordUsageRequest\x1a\x1f.novel.auth.RecordUsageResponseB>\n(com.novel.auth.infrastructure.grpc.protoB\x10\x41uthServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.novel.auth.infrastructure.grpc.protoB\020AuthServiceProtoP\001'
  _globals['_VERIFYTOKENREQUEST']._serialized_start=34
  _globals['_VERIFYTOKENREQUEST']._serialized_end=69
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=71
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=156
  _globals['_CHECKQUOTAREQUEST']._serialized_start=158
  _globals['_CHECKQUOTAREQUEST']._serialized_end=210
  _globals['_CHECKQUOTARESPONSE']._serialized_start=212
  _globals['_CHECKQUOTARESPONSE']._serialized_end=286
  _globals['_RECORDUSAGEREQUEST']._serialized_start=288
  _globals['_RECORDUSAGEREQUEST']._serialized_end=390
  _globals['_RECORDUSAGERESPONSE']._serialized_start=392
  _globals['_RECORDUSAGERESPONSE']._serialized_end=430
  _globals['_AUTHSERVICE']._serialized_start=433
  _globals['_AUTHSERVICE']._serialized_end=683
# @@protoc_insertion_point(module_scope)
